### ISSUE TITLE
Últimos arreglos a la plataforma

### ISSUE THREAD

**Issue by andreamarianalm** [Laboratoria/awesome-rank#77]
@ivandevp 

- [x] Cambiar el font size de las estrellas a 11px.
- [x] Cambiar a gris (#2B2B2B) los títulos como Emotional Status y a 1.3rem 
- [x] Quitar el tooltip (i) de los títulos
- [x] Agrandar títulos como STRESS MANAGEMENT a font size 13px
- [x] Bold al botón SEND
- [x] Que cuando se de clic a Soft Skills y Technical Skills, se centre la pantalla para evaluar (desde el título de la sección hacia abajo)

**Comment by diegovelezg** [comment]
@ivandevp  Por favor danos de una vez los accesos a la DB!!!!!

**Comment by ivandevp** [comment]
@diegovelezg Te los mandé a tu correo hace tiempo, te lo reenvío.

**Comment by ivandevp** [comment]
@andreamarianalm El font-size de las estrellas es muy pequeño.

**Comment by ivandevp** [comment]
@andreamarianalm @diegovelezg  los cambios fueron realizados a excepción del tamaño de las estrellas, chequen bien si ese realmente es el tamaño que desean.

[Aquí](http://hackathon.laboratoria.la/) lo pueden ver.

**Comment by andreamarianalm** [comment]
Gracias por los cambios, @ivandevp !
Sobre los font-size:
- Los títulos como STRESS MANAGEMENT, a 15px (perdón por este cambio!)
- Las estrellas a 3.5rem (no sé por qué ahora me sale en esta medida :O)

Con algunos celulares Android se rompe el diseño de las estrellas (una estrella se pasa para abajo), entonces si le bajamos un poquito el tamaño espero que ya no se rompa (cuando nos des el ok, lo testeamos aquí en varios celulares y te cuento). 

Me cuentas! El jueves nosotros subimos el contenido y te contamos cómo va!

**Comment by diegovelezg** [comment]
Auxilio @ivandevp 

![image](https://user-images.githubusercontent.com/28717078/27931707-c70bdc36-6260-11e7-954a-8330cdba2d0c.png)

**Comment by ivandevp** [comment]
Listo, cambios realizados. Pueden checar como se ve en algunos móviles [aquí](http://www.responsinator.com/?url=hackathon.laboratoria.la). Me comentan si queda para lanzar el Pull Request y cerrar este issue.
